/**
 * Migration: Create the `users` table.
 *
 * This is the foundational table for authentication and identity.
 * All other entities reference users via foreign keys.
 *
 * Columns:
 *   - id          UUID primary key
 *   - username    unique, required login identifier
 *   - email       optional contact email (unique when provided)
 *   - password    Argon2-hashed password
 *   - created_at  timezone-aware creation timestamp
 *   - updated_at  timezone-aware last-update timestamp
 */

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const up = (knex) => {
  return knex.schema.createTable("users", (table) => {
    // Primary key — UUID generated by the application layer
    table.uuid("id").primary()

    // Login identifier — must be unique across the system
    table.string("username").notNullable().unique()

    // Optional email for invitations and notifications
    table.string("email", 255).unique().nullable()

    // Argon2-hashed password — never stored in plain text
    table.string("password").notNullable()

    // Failed login tracking for per-user account lockout
    table.integer("failed_login_attempts").notNullable().defaultTo(0)
    table.timestamp("locked_until").nullable()

    // Timezone-aware timestamps managed by Knex
    table.timestamps(true, true)
  })
}

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const down = (knex) => {
  return knex.schema.dropTable("users")
}
