/**
 * Migration: Create the `refresh_tokens` table.
 *
 * Stores SHA-256 hashes of issued refresh tokens to support:
 * - Token rotation on use (C5)
 * - Token revocation / logout (H1)
 *
 * Columns:
 *   - id          UUID primary key (auto-generated)
 *   - user_id     FK to users.id (CASCADE delete)
 *   - token_hash  SHA-256 hash of the refresh token
 *   - expires_at  when the token becomes invalid
 *   - revoked_at  when the token was revoked (null if active)
 *   - created_at  timezone-aware creation timestamp
 *   - updated_at  timezone-aware last-update timestamp
 */

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const up = (knex) => {
  return knex.schema.createTable("refresh_tokens", (table) => {
    // Primary key — UUID generated by PostgreSQL
    table.uuid("id").primary().defaultTo(knex.raw("gen_random_uuid()"))

    // The user this refresh token belongs to
    table.uuid("user_id").notNullable()
    table.foreign("user_id").references("id").inTable("users").onDelete("CASCADE")

    // SHA-256 hash of the issued refresh token
    table.string("token_hash", 64).notNullable()

    // When this refresh token expires
    table.timestamp("expires_at", { useTz: true }).notNullable()

    // When this refresh token was revoked (null if still active)
    table.timestamp("revoked_at", { useTz: true }).nullable()

    // Timezone-aware timestamps
    table.timestamps(true, true)

    // Index for finding all tokens belonging to a user
    table.index("user_id")

    // Index for looking up tokens by hash during refresh/logout
    table.index("token_hash")
  })
}

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const down = (knex) => {
  return knex.schema.dropTable("refresh_tokens")
}
